apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels: 
    component: web
spec:
  containers:
    - name: client
      image: bradmasy/multi-client-10-14:latest
      ports:
        - containerPort: 3000
